# Generated by Django 4.1.7 on 2023-03-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=1)),
                ('pais_origen', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
