# Generated by Django 4.1.7 on 2023-03-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='uid',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
